import mongoose from "mongoose";

const userOTPSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    otp: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

// TTL Index on createdAt (automatically generated by timestamps)
userOTPSchema.index({ createdAt: 1 }, { expireAfterSeconds: 300 }); // 5 minutes

const UserOTPSchema = mongoose.model("UserOTP", userOTPSchema);
export default UserOTPSchema;
